name: boostsecurity.io
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - labeled
      - synchronize
permissions: {}
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to scan'))
    steps:
      - run: |
          cat $GITHUB_EVENT_PATH
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          GITHUB_EVENT_NAME: ${{ fromJSON('{"push":"push","pull_request_target":"pull_request"}')[github.event_name] || github.event_name }}
          GITHUB_REF_NAME: ${{ github.event.pull_request.head.ref }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/native-scanner
