name: boostsecurity.io
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - labeled
      - synchronize
permissions: {}
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to scan') }}
    steps:
      - run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          GITHUB_EVENT_NAME: pull_request
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/native-scanner
          log_level: TRACE
