name: boostsecurity.io
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
permissions: {}
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_EVENT_NAME
      - run: |
          cat $GITHUB_EVENT_PATH
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          cli_version: 1.0.0.rc138
          registry_module: boostsecurityio/native-scanner
          log_level: TRACE
